### ISSUE TITLE
wssagent is unreachable

### ISSUE THREAD

**Issue by KamalAman** [Azure/iotedge-eflow#31] opened 2021-06-18 13:59 UTC
**Describe the bug**
Installing EFLOW on Windows 10 Pro Build 19041 is unsuccessful due to wssagent being unreachable.
There is no service called WSS Agent installed in WIndows

**To Reproduce**
Install EFLOW on said build

**Expected behavior**
Installation should be successful

**Windows Host OS (please complete the following information):**
 - Edition: Professional
 - Version: 19041
 - Virtual Machine: None

**Comment by KamalAman** [comment] 2021-06-18 15:02
Hi @fcabrera23 

I tried both the WAC and PowerShell deployment methods. Both failed with the same error. 
For the switch, i am using whatever the default selection is in the user interface. 
I think i t said External

I'll export the Logs now

**Comment by fcabrera23** [comment] 2021-06-18 15:05
Hi @KamalAman,

Thanks for your quick response. Can you try cleaning any EFLOW installation, reboot your machine and try again? Please uninstall EFLOW following these steps:

a. Open Settings on Windows 10
b. Select Add or Remove Programs
c. Select Azure IoT Edge app
d. Click Uninstall button

**Comment by KamalAman** [comment] 2021-06-18 15:10
Output of the logs are 

```
Get-EflowLogs 

[06/18/2021 11:07:56] Exception caught!!!
 - wssdagent is unreachable, please retry... at line 3493
```

I can try to uninstall, reboot, and reinstall shortly. 

Is there a way to manually install the WSS Agent? 
Since it is not listed in Windows Services

**Comment by johnsonshih** [comment] 2021-06-18 19:19
Hi @KamalAman
  can you describe the repro steps in more details?  In the case of installing eflow msi, there is no step to invoke wssdagent.  What's the step you ran and saw the error? Have you ran deploy-eflow to deply eflow to your machine?

**Comment by fcabrera23** [comment] 2021-06-28 18:14
@biaojiang,

Which version of PowerShell are you using? Are you using the latest MSI? Can you please uninstall using Add & Remove programs and then re-install?

Thanks,
Francisco

**Comment by TerryWarwick** [comment] 2021-06-29 04:27
@biaojiang & @KamalAman,

This issue was originally reported on June 17, and at that time you were using our Public Preview installer.  On June 23rd we released EFLOW for general availability for use in production.  It is no longer in preview.  As part of this release it is critical that you uninstall the Public Preview using Start - Settings - Apps then select Azure IoT Edge from the list of installed applications and remove.

Once removed, please retry installation using the instructions available at https://aka.ms/AzEFLOW-install.  If you continue to encounter an issue with the reinstall, please open a new issue with the details of the issue that you encounter.

Terry Warwick
Microsoft

**Comment by biaojiang** [comment] 2021-06-29 06:17
Hi, @fcabrera23, my Powershell version is 5.1.19041.1023.

@TerryWarwick , before I installed EFLOW, I did uninstall the preview version, but the problem is that I couldn't cleanly uninstall the preview version of Azure IoT Edge in Windows 10 from `Start - Settings - Apps` , pls check the following information:

1.  First, I tried to uninstall it in Apps&Features. However, after that, the `Azure IoT Edge` app is still under "Apps", as shown in the following image:
![iot_edge_in_apps-and-features](https://user-images.githubusercontent.com/18609133/123213101-e3c64600-d4c5-11eb-9b31-0a92a655f36f.PNG).

So I used `registry editor` to deleted the Azure IoT Edge entries, then `Azure IoT Edge` disappeared in `Apps`.

2. Secondly, I ran the command in PowerShell Admin, and got the following results:
![uninstall_iot_edge](https://user-images.githubusercontent.com/18609133/123213240-0e180380-d4c6-11eb-96f0-71c7eaf791a3.PNG)

3. Then I tried to create a new IoT Edge with `Windows Admin Center`, and got the following error:
![create_new_iot_edge_error](https://user-images.githubusercontent.com/18609133/123213713-9f877580-d4c6-11eb-915e-71bfecec8e1e.PNG)

Have no idea how to fully uninstall the Azure IoT Edge, `Windows Admin Center` always detected the Azure IoT Edge in my computer. I think this is the reason I can't install ELFLOW.

**Comment by fcabrera23** [comment] 2021-06-29 17:01
@biaojiang,

Could you please check if you have logs .zip file under the Azure IoT Edge folder located at `C:\Program Files\Azure Iot Edge`. Also, if you have that folder, means that your installation was not completed, and you should remove that also. 

Thanks,
Francisco

**Comment by biaojiang** [comment] 2021-06-30 07:49
@fcabrera23 , I found some log files in my Users directory and deleted them, now both `Windows Admin Center` and `ELFLOW` can deploy the VM without errors, and I used `ELFLOW`. So, later we always use `ELFLOW` to deploy VM?

**Comment by fcabrera23** [comment] 2021-07-01 14:00
@biaojiang,

Thanks for your information - Could you please answer a couple of questions.

1. Go to Hyper-V Manager and check you don't have any old EFLOW VM running - If present, please delete the VM
2. Go to Hyper-V Manager - Virtual Switch Manager - Confirm you have a Default Switch - If not present, create a new one
3. Go to C:\Program Files - Confirm you don't have a Azure IoT Edge folder - If present, remove the installation from Add & Remove Programs
4. Go to Add & Remove Programas - Confirm you don't have a Azure IoT Edge installation - If present, remove it.

Once you check all that, please follow the instructions [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=powershell)

**Comment by biaojiang** [comment] 2021-07-02 07:11
Now I solved the problem, the SSH connection is OK. I changed back the ExecutionPolicy of the LocalMachine to the default value of `RemoteSigned`, didn't execute the command `Set-ExecutionPolicy -ExecutionPolicy AllSigned -Force` in the [instructions](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart?view=iotedge-2018-06&viewFallbackFrom=iotedge-2020-11), then the deployment was successful.
Now you can close the issue. @fcabrera23

**Comment by fcabrera23** [comment] 2021-07-06 13:42
@biaojiang,

Can you try executing the `Connect-EflowVm` command using an elevated PowerShell session, and having the ExecutionPolicy set to _AllSigned_? 

Thanks,
Francisco

**Comment by biaojiang** [comment] 2021-07-06 14:15
@fcabrera23 ,
Yes, now I set `AllSigned`, then got a SSH connection timed out error: `ssh : ssh: connect to host xxx.xxx.xxx.xxx port 22: Connection timed out`

![ssh error](https://user-images.githubusercontent.com/18609133/124614903-06b50a80-de75-11eb-817c-6460b654e28f.PNG)

So is it the `firewall` setting problem? but I can SSH to the Linux VM without any problem.

**Comment by fcabrera23** [comment] 2021-07-20 13:30
Hi @biaojiang,

It seems the problem is related to networking rather than the firewall. Can you try the following? (Always using PowerShell, not PowerShell ISE)

1. Reboot the Windows host and try again
2. Check the IP of the EFLOW VM using the command `Get-EflowVmAddr`

**Comment by biaojiang** [comment] 2021-07-24 14:43
Hi, @fcabrera23, I did use PowerShell not PS ISE, and when I run `Get-EflowVmAddr`, I could get the VM IP, but just can't connect with `Connect-EflowVm`.

I also tried to deploy VM by using `Windows Admin Center`, it didn't work as well, the VM can be deployed successfully, but can't see the Linux terminal.

**Comment by fcabrera23** [comment] 2021-07-27 18:39
Thanks for your information @biaojiang. EFLOW extension for Windows Admin Center does not support the Bash terminal anymore due to security concerns.  Some further questions

- Are you using the same system that you manually delete eflow files previously?
- Can you try on a different system without any EFLOW installed previously?

**Comment by biaojiang** [comment] 2021-08-01 19:57
Hi, @fcabrera23, yes, I used the same system. I'll pause this work now, I think it is my computer security setting problem. I will try EFLOW in an Azure Windows VM later. Now you can close this issue, tks.

**Closed** 2021-08-02 00:51 UTC

**Comment by paulbrittain** [comment] 2022-07-27 10:31
Hello, I've successfully installed, provisioned, and connected to an EFLOW VM on an Azure Windows VM. So I want to chime in here and confirm that it's possible.

**Comment by luukdekinderenIS** [comment] 2025-01-27 10:13
I encountered a similar issue during the installation of IoT Edge. I received the error message: Failed to start service 'WSSD Agent Service (wssdagent)'.

It’s important to note that I don’t think my issue is the same as the one described above. However, I wanted to share my findings here in case someone is searching for solutions related to problems with the WSSD Agent. My solution might be helpful in their situation. Here’s what I did:

I checked the file located at C:\ProgramData\wssdagent\log\wssdagent.log. In the log, I found a line indicating that the following file was being read:
C:\ProgramData\wssdagent\v0.10.8-alpha.10\config.yaml.

However, that file didn’t exist at all, and there where no other logs in de logfile. I copied the file from another computer with IoT Edge installed, and afterward, I was able to complete the IoT Edge installation successfully.

Why this issue occurred on this specific machine remains a mystery to me. Even after a complete reinstallation of Windows, the problem persisted. And a manual copy of the file is needed. I hope this post is helpful to someone! Good luck.
