### ISSUE TITLE
[Hyper-V] Installation of virtual switch failed during deploying Azure IoT edge Linux on Windows

### ISSUE THREAD

**Issue by arminghasemazar** [Azure/iotedge-eflow#59] opened 2021-08-02 05:24 UTC
I'm using latest version of WAC and its extensions all installed on the latest version of Windows Server 2019. Hyper-V has been installed and is running. When I deploy a new Azure IoT Edge for Linux on Windows on host (same PC) using default setting recommended by WAC, I ran into an error of "Error: Installation of virtual switch failed".

I already checked event viewer and below is what it shows:

```
Log Name:      Microsoft-ServerManagementExperience
Source:        UI
Date:          7/26/2021 12:35:46 PM
Event ID:      2
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      XXX
Description:
sessionId : 52a7f5bc-872c-4e95-ae8f-de9faa105039
eventId : Trace
level : Error
sourceName : Microsoft.AzureIoTEdge
source : EflowCreateWizard
timestamp : 1627295715557
message : DeployStepComponent
stack : 
moreEventData : 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="UI" />
    <EventID Qualifiers="0">2</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-07-26T10:35:46.173052100Z" />
    <EventRecordID>2590</EventRecordID>
    <Channel>Microsoft-ServerManagementExperience</Channel>
    <Computer>XXX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sessionId : 52a7f5bc-872c-4e95-ae8f-de9faa105039
eventId : Trace
level : Error
sourceName : Microsoft.AzureIoTEdge
source : EflowCreateWizard
timestamp : 1627295715557
message : DeployStepComponent
stack : 
moreEventData : </Data>
  </EventData>
</Event>
```

When I check Hyper-V manager, I can see that a virtual switch has already been made after I installed Hyper-V. So I don't see any error with Hyper-V. But clearly WAC cannot create a virtual switch that it apparently needs. Would you please help me find the solution?

**Comment by arminghasemazar** [comment] 2021-08-03 11:12
@TerryWarwick I posted a new issue as requested.

**Comment by fcabrera23** [comment] 2021-08-03 12:37
@arminghasemazar,

Thanks for your detailed information. Our current EFLOW version has a bug with Windows Server that will prevent deployment completion.  We are working on an update that we hope to publish this week that will allow you to override our use of Default Switch.  This will add a couple of parameters to the Deploy-EFLOW command where you will specify the name and type of vSwitch you want to use.  You will need to create and configure the vSwitch ahead of time as there are enterprise network implications that come into play.  Once the update is available there will be release notes available at [EFLOW Releases](https://aka.ms/AzEflow-Releases).

**Comment by fcabrera23** [comment] 2021-08-04 13:00
Hi @arminghasemazar,

We have released our latest EFLOW update that adds the functionality to assign a virtual switch during EFLOW Deployment. In the case of Windows Server, users will have to [create a virtual switch](https://docs.microsoft.com/azure/iot-edge/how-to-create-virtual-switch) prior to EFLOW installation.  For more information on our latest update, check 1[.1.2107.0 Release Notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0).

Thanks,
Francisco

**Comment by arminghasemazar** [comment] 2021-08-04 13:45
Hi @fcabrera23. Just installed fresh WAC, updated all extensions and tried to add an IoT edge deployment. WAC still fetches the old EFLOW version. See below the screenshot. 

![image](https://user-images.githubusercontent.com/13336488/128191701-d2a78f97-cae4-4eb8-b217-10f59ae95e4c.png)

**Comment by fcabrera23** [comment] 2021-08-04 14:00
Hi @arminghasemazar,

The update is still being released and takes some time to be available. Can you try in approximately 3-6 hours?

Thanks,
Francisco

**Comment by fcabrera23** [comment] 2021-08-04 17:49
Hi @arminghasemazar,

If you are using Windows Server, make sure to create a switch before deploying EFLOW. For more information check [Azure IoT Edge for Linux on Windows virtual switch creation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-virtual-switch?view=iotedge-2018-06).

Thanks,
Francisco

**Comment by arminghasemazar** [comment] 2021-08-05 07:36
Hi @fcabrera23. I just did another round of test. virtual switch is already there (default). I see a strange error now, which doesn't give much information. Also I can't find any WAC log to dig into. see screenshot. The only log I can find is inside the Windows Event viewer, where there is an Error line, again with no valuable information. I'm using Azure IoT edge default setting for deployment. I also tested on Windows 10 (latest) but the same error happens. 

![image](https://user-images.githubusercontent.com/13336488/128307671-5ebec8e4-2176-444e-9158-d0e0969f9cdc.png)

```
Log Name:      Microsoft-ServerManagementExperience
Source:        UI
Date:          8/5/2021 7:12:36 AM
Event ID:      2
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      XXX
Description:
sessionId : 7c80f5e4-b02e-4067-81fb-f87b47313b55
eventId : Trace
level : Error
sourceName : Microsoft.AzureIoTEdge
source : EflowCreateWizard
timestamp : 1628147526570
message : DeployStepComponent
stack : 
moreEventData : 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="UI" />
    <EventID Qualifiers="0">2</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-08-05T07:12:36.584486400Z" />
    <EventRecordID>809</EventRecordID>
    <Channel>Microsoft-ServerManagementExperience</Channel>
    <Computer>XXX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sessionId : 7c80f5e4-b02e-4067-81fb-f87b47313b55
eventId : Trace
level : Error
sourceName : Microsoft.AzureIoTEdge
source : EflowCreateWizard
timestamp : 1628147526570
message : DeployStepComponent
stack : 
moreEventData : </Data>
  </EventData>
</Event>
```

**Comment by fcabrera23** [comment] 2021-08-05 11:58
@arminghasemazar, 

- Are you still using Windows Server? Which Windows build are you using?
-  Could you try using PowerShell?
- Could you please share a capture of your network switches?

Thanks,
Francisco

**Comment by arminghasemazar** [comment] 2021-08-05 16:57
@fcabrera23 

So after trying many ways (updating Windows server 2019 to latest version), installing EFLOW via PowerShell many times, ..., I could a couple of steps forward but I'm now facing new issue in the latest steps. See screenshot. Seems like SSH cannot to VM. Any clue?

OS Name	Microsoft Windows Server 2019 Standard, Version 10.0.17763 Build 17763 (fully updated)

See below also Hyper-V switch configuration
![image](https://user-images.githubusercontent.com/13336488/128390324-d2db9ee9-421c-4086-bae1-dfbbbba3481e.png)
![image](https://user-images.githubusercontent.com/13336488/128390572-5e9520c4-6f72-4587-966f-c6c7e2505300.png)

**Comment by TerryWarwick** [comment] 2021-08-05 17:06
@arminghasemazar,

Please turn on Internet Connection Sharing (ICS) if it is not already.  I am pretty sure that this switch will be attempting to sharing the NIC with the host.

Terry Warwick
Microsoft

**Comment by arminghasemazar** [comment] 2021-08-06 07:29
@TerryWarwick ICS is already enabled. See below. But I don't think ICS has anything to do with SSH. Below is error I face. 

```
[08/06/2021 07:24:01] Querying IP and MAC addresses from virtual machine (OSI8276-EFLOW)

 - Virtual machine MAC: 00:15:5d:65:21:b8
 - Virtual machine IP : 172.28.57.30

[08/06/2021 07:24:47] Testing SSH connection...

[08/06/2021 07:26:53] SSH channel cannot be initialized due to fail to create known hosts file

[08/06/2021 07:26:53] Exception caught!!!

 - Unable to connect virtual machine with SSH. Aborting...
Please uninstall Azure IoT Edge for Linux on Windows, ensure virtual machines can obtain an IP address through the Default Switch, and re-attempt installation. (L1522)
```

![image](https://user-images.githubusercontent.com/13336488/128473467-196b8800-32d3-4f22-913d-29eef18a9057.png)

**Comment by Karamveer13** [comment] 2021-08-10 18:09
Is there any update on this ssh issue? M facing same issue

**Comment by mksp2016** [comment] 2021-08-10 21:32
We are facing the same issue, any update on that?

**Comment by fcabrera23** [comment] 2021-08-11 15:50
@Karamveer13,

Are you using Internal or External Switch? Have you created the switch using the [Azure IoT Edge for Linux on Windows virtual switch creation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-virtual-switch?view=iotedge-2018-06) guide?

Also, if you are using Internal Switch, can you check if the DHCP server has all the required permissions? You can check this by typing DHCP inside Windows search, and then checking the IPv4 status. 

Thanks,
Francisco

**Comment by fcabrera23** [comment] 2021-08-11 15:50
@mksp2016,

Are you using Internal or External Switch? Have you created the switch using the [Azure IoT Edge for Linux on Windows virtual switch creation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-virtual-switch?view=iotedge-2018-06) guide?

Also, if you are using Internal Switch, can you check if the DHCP server has all the required permissions? You can check this by typing DHCP inside Windows search, and then checking the IPv4 status. 

Thanks,
Francisco

**Comment by Karamveer13** [comment] 2021-08-11 16:21
Hi @fcabrera23 
I'm much very much new to this. Though I'm not getting DHCP option. Its windows 10 Pro OS for me. Switch was default switch. I'm putting up screenshot below for the IPv4 setting for default switch. Please suggest if i can get step by step process:


![Screenshot1](https://user-images.githubusercontent.com/62113173/129066128-0228f195-5072-4e62-9a66-479a08b41284.JPG)
![screenshot2](https://user-images.githubusercontent.com/62113173/129066145-d0afc783-d51f-4c93-b8a3-aaae25438ac9.JPG)

**Comment by fcabrera23** [comment] 2021-08-11 16:30
Hi @Karamveer13,

Thanks for your clarification. My suggestions would be the following.

1. Remove the static IP configuration from your Default Switch and try the installation again.  This will help us determine if the problem is related to your configuration or another problem. 
2. If that works, then you can use a Static IP using the Deploy-Eflow command. Please check [PowerShell functions for IoT Edge for Linux on Windows](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06) for full documentation.

Thanks, 
Francisco

**Comment by fcabrera23** [comment] 2021-08-11 16:58
@Karamveer13,

We have a [EFLOW Wiki](https://github.com/Azure/iotedge-eflow/wiki) that has lots of FAQ. In order to uninstall, follow these steps:

1. Open Settings on Windows 10
2. Select Add or Remove Programs
3. Select Azure IoT Edge app
4. Select Uninstall

We do not provide a way to uninstall using PowerShell.

Thanks,
Francisco

**Comment by Karamveer13** [comment] 2021-08-12 05:41
@fcabrera23 
I tried reinstalling after disabling static IP on default switch and got this error:
![screenshot3](https://user-images.githubusercontent.com/62113173/129143987-137fdf81-f84d-432c-8c8d-2e6dfa4fa273.JPG)

**Comment by fcabrera23** [comment] 2021-08-12 13:50
@Karamveer13,

It seems that you are having issues getting an IP from the Default Switch. Is your computer domain joined? Do you have some kind of security policy that could be blocking this?

Also, what was the command used to install eflow, can you share that?

Thanks,
Francisco

**Comment by mksp2016** [comment] 2021-08-12 18:36
@fcabrera23 We have 15 devices where we need to deploy EFLOW. Till last week we were able to install EFLOW in 5 devices successfully but now since last week we have been getting error while deploying from admin center. 
We have same configuration for all the devices. 
it seems recent update/release is breaking.

**Comment by fcabrera23** [comment] 2021-08-12 20:43
@mksp2016,

We were having some issues with our WAC Deployment functionality. It should be fixed now. Please take into consideration that WAC will install the 1.1.2106.1 version, and you can get the latest update (1.1.2107.0) through Windows Update. 

We are working on bringing WAC support to the latest version. Once we have an update to WAC Extension, no update will be needed. If you want to install the latest version from scratch, you can always use our PowerShell installation.

Thanks,
Francisco

**Comment by Karamveer13** [comment] 2021-08-15 12:07
@fcabrera23 
Though i was able to deploy VM and take ssh after reinstalling but the problem is, after every reboot, default switch and vm ip get change and then I'm not able to ssh into EFLOW vm

**Comment by fcabrera23** [comment] 2021-08-16 13:04
Hi @Karamveer13,

If you are not using static IP, the Default Switch IP will change with every reboot. However, we do support static IP for Default Switch on Client SKU's. To use a Static IP, use the Deploy-Eflow command. Please check [PowerShell functions for IoT Edge for Linux on Windows](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06) for full documentation.

Thanks,
Francisco

**Closed** 2021-08-25 14:31 UTC
