### ISSUE TITLE
EflowAutodeploy script Error

### ISSUE THREAD

**Issue by srjhunjhunwalacorp** [Azure/iotedge-eflow#185] opened 2022-10-11 11:58 UTC
**Describe the bug**
Latest Eflowautodeploy script is giving error, shows the deployment successful but failed while setting proxy and dns at the end.

**To Reproduce**
1. Install eflow using the autodeploy script
2. I have used following parameters ( obfuscated few parameters with xx)

{
    "schemaVersion":"1.1",
    "version":"1.0",
    "eflowProduct" : "Azure IoT Edge CR X64",
    "eflowProductUrl" : "https://aka.ms/AzEFLOW-X64-1_2_10_09062",
    "installOptions":{
        "installPath":"",
        "vhdxPath":""
    },
    "enduser":{
        "acceptEula" : "Yes",
        "acceptOptionalTelemetry" : ""
    },
    "network":{
        "adapterName": "Ethernet",
        "vswitchName" : "Eflowswitch",
        "vswitchType" : "Internal",
        "ip4Address": "169.254.172.15",
        "ip4GatewayAddress": "169.254.172.1",
        "ip4PrefixLength" : "24",
        "useHostProxy" : true,
        "httpProxy":"http://xx",
        "httpsProxy":"https://xx",
        "ftpProxy" :"",
        "dnsServers":"xx"
    },
    "vmConfig":{
        "cpuCount" : 2,
        "memoryInMB" : 4096,
        "vmDiskSize" : 0,        
        "gpuPassthroughType" : "",
        "gpuName" : "",
        "gpuCount" : 0
    },
    "vmFeature":{
        "DpsTpm": false,
        "Defender": false
    },
    "eflowProvisioning":{
        "provisioningType" : "ManualConnectionString",
        "devConnString" : "xx",
        "iotHubHostname" : "xx",
        "deviceId" : "xx",
        "scopeId" : "",
        "symmKey": "",
        "registrationId" : "",
        "identityCertPath" : "",
        "identityPrivKeyPath" : "",
        "globalEndpoint" : ""
    }
}

**Expected behavior**
After successful deployment edge modules loads successfully to Eflow.

**Screenshots**
![image](https://user-images.githubusercontent.com/64076463/195082265-1e96e686-1317-437f-898d-fd724f0cd5e4.png)

**Windows Host OS (please complete the following information):**
Edition: Windows Server 2019
Virtual Machine: Azure VM
 
**Additional context**

**Comment by srjhunjhunwalacorp** [comment] 2022-10-13 04:56
> Hi @srjhunjhunwalacorp,
> 
> I was able to reproduce your issue and fix the deployment script. Could you please try again with the latest version of the deployment script?
> 
> Thanks, Francisco

Thanks Francisco

I tried the new deployment script and got following error- 


![image](https://user-images.githubusercontent.com/64076463/195505138-33063539-7670-4d5e-a237-30cad0883f26.png)

**Comment by fcabrera23** [comment] 2022-10-13 14:09
Hi @srjhunjhunwalacorp,

Sorry, there was another issue introduced with the previous changes. Issues are now fixed and tested with the configuration shared.  Also, you're using the EFLOW CR 1.2.10 version, but there's a newer version 1.3.1 available, so I'd suggest changing that. 

Thanks,
Francisco

**Comment by srjhunjhunwalacorp** [comment] 2022-10-14 04:31
> Hi @srjhunjhunwalacorp,
> 
> Sorry, there was another issue introduced with the previous changes. Issues are now fixed and tested with the configuration shared. Also, you're using the EFLOW CR 1.2.10 version, but there's a newer version 1.3.1 available, so I'd suggest changing that.
> 
> Thanks, Francisco

I have now tested with new version - "https://aka.ms/AzEFLOW-X64-1_3_1_02092", but deployment failed in the last stage. I have used the same configuration only change is eflowProductURL.

![image](https://user-images.githubusercontent.com/64076463/195762693-d681ed1f-f0c5-4a96-b418-1306aa083ffc.png)

Thanks

**Comment by fcabrera23** [comment] 2022-10-14 13:01
@srjhunjhunwalacorp,

Thanks for the update - Can you try connecting to the VM using Connect-EflowVm and check if the modules are running? I suspect there's a timing issue but the VM is up and running and correctly configured. 

Thanks,
Francisco

**Comment by srjhunjhunwalacorp** [comment] 2022-10-14 13:13
> @srjhunjhunwalacorp,
> 
> Thanks for the update - Can you try connecting to the VM using Connect-EflowVm and check if the modules are running? I suspect there's a timing issue but the VM is up and running and correctly configured.
> 
> Thanks, Francisco

Hi Francisco,

I checked by getting into EflowVM but modules were not running , I can try once more on Monday and confirm you?

Rgds
Sid

**Comment by Amber-Rigg** [comment] 2022-10-17 10:02
Hello Francisco,

I have attempted the same deployment on a clean machine, I am seeing the same error as Sid and no modules are running.

Running an iotedge check we can see there is no connection but the proxy is showing as being configured.

Running nslookup I can see the device has connection to the internet.

We would really appreciate your help with this.

Many thanks,

Amber

![image](https://user-images.githubusercontent.com/44523299/196146135-105e63db-ea0b-4047-b9c7-25ddb85fa627.png)

![image](https://user-images.githubusercontent.com/44523299/196149116-c3d411e9-a8dd-46e4-9720-1c3990d9234b.png)

**Comment by fcabrera23** [comment] 2022-10-17 15:25
Hi @Amber-Rigg,

Could you please share the config json you're using? Please make sure to remove any confidential information before sharing.

Thanks,
Francisco

**Comment by fcabrera23** [comment] 2022-10-17 19:20
Hi @Amber-Rigg @srjhunjhunwalacorp,

Just pushed some more changes - Tried a couple of scenarios and all worked. Could you please download the latest version and try again? Thanks

**Comment by srjhunjhunwalacorp** [comment] 2022-10-18 08:47
> Hi @Amber-Rigg @srjhunjhunwalacorp,
> 
> Just pushed some more changes - Tried a couple of scenarios and all worked. Could you please download the latest version and try again? Thanks

Hi Francisco,

I tried the new version but still the same, Eflow VM installed without any issue but there is no connectivity to the internet.

Following is the configuration I am using, removed the proxy and DNS - 

{
    "schemaVersion":"1.1",
    "version":"1.0",
    "eflowProduct" : "Azure IoT Edge CR X64",
    "eflowProductUrl" : "https://aka.ms/AzEFLOW-X64-1_3_1_02092",
    "installOptions":{
        "installPath":"",
        "vhdxPath":""
    },
    "enduser":{
        "acceptEula" : "Yes",
        "acceptOptionalTelemetry" : ""
    },
    "network":{
        "adapterName": "Ethernet",
        "vswitchName" : "Eflowswitch",
        "vswitchType" : "Internal",
        "ip4Address": "xxxx",
        "ip4GatewayAddress": "xxxx",
        "ip4PrefixLength" : "24",
        "useHostProxy" : true,
        "httpProxy":"xxxx",
        "httpsProxy":"xxxx",
        "ftpProxy" :"",
        "dnsServers":"xxxx"
    },
    "vmConfig":{
        "cpuCount" : 2,
        "memoryInMB" : 4096,
        "vmDiskSize" : 0,
        "vmDataSize" : 0,
        "gpuPassthroughType" : "",
        "gpuName" : "",
        "gpuCount" : 0
    },
    "vmFeature":{
        "DpsTpm": false,
        "Defender": false
    },
    "eflowProvisioning":{
        "provisioningType" : "ManualConnectionString",
        "devConnString" : "xxxx",
        "iotHubHostname" : "xxxx",
        "deviceId" : "xxxx",
        "scopeId" : "",
        "symmKey": "",
        "registrationId" : "",
        "identityCertPath" : "",
        "identityPrivKeyPath" : "",
        "globalEndpoint" : ""
    }
}

**Comment by Amber-Rigg** [comment] 2022-10-18 11:03
> Hi @Amber-Rigg @srjhunjhunwalacorp,
> 
> Just pushed some more changes - Tried a couple of scenarios and all worked. Could you please download the latest version and try again? Thanks

Hello Francisco,

I have also tried the new deployment script and I am seeing issues. To confirm I am trying to deploy eflow on IoT Edge 1.3 as from my understanding 1.4 for EFlow has yet to be released.

The deployment script is currently running successfully and no error is outputted. However once connected to the EFlow VM I can see there is no internet connection and the edgeAgent and edge Hub are not running.

I also investigated the config.toml and found no proxy configuration set here on the edgeAgent, there were no edgeAgent configurations at all. I added the proxy to the config.toml to see if this would help however it made no difference.

As the EFlow VM is not connecting to the internet I wonder if the issue is with the DNS and not proxies as in the past setting the DNS has allowed internet access. For IoTEdge 1.1 I have previously used the command:

`Invoke-EflowVmCommand "echo DNS=x.x.x.x | sudo tee /etc/systemd/resolved.conf -a && sudo systemctl restart systemd-resolved && sudo systemctl restart docker"`

To allow for internet access and the DNS to be set, is there an equivalent command for 1.3?

Many thanks,

Amber

![image](https://user-images.githubusercontent.com/44523299/196411448-9e77d5d2-6eed-4132-8dd3-7ff3a975e0bb.png)

![image](https://user-images.githubusercontent.com/44523299/196411488-23e41760-b9e7-4bfb-8241-1aaa1c469ba4.png)

Original config.toml

```
iotedge-user@AEWNW00042DIOT3-EFLOW [ ~ ]$ sudo cat /etc/aziot/config.toml
additional_info="file:///etc/product-info.toml"
# ==============================================================================
# Hostname
# ==============================================================================
#
# Uncomment the next line to override the default hostname of this device.
#
# hostname = "my-device"

# ==============================================================================
# Local Gateway Hostname
# ==============================================================================
#
# If this device is running in a nested deployment, uncomment the next line to
# set the local gateway hostname of this device.
#
# local_gateway_hostname = "my-parent-device"

# ==============================================================================
# Cloud Timeout and Retry Behavior
# ==============================================================================
#
# These settings control the timeout and retries for cloud operations, such as
# communication with DPS during provisioning or IoT Hub for module identity creation.
#
# cloud_timeout_sec is the deadline (in seconds) for a network request (such as
# an HTTP request) to the aforementioned cloud services. A response from the cloud
# must be received before this deadline, or the request will fail as timed out.
#
# cloud_retries controls how many times a request may be retried should it fail.
# The client will always send at least one attempt, so its value will be the number
# of retries after the first attempt should that fail (i.e. cloud_retries = 2
# means that the client will make a total of 3 attempts).
#
# cloud_timeout_sec = 10
# cloud_retries = 1

# ==============================================================================
# Provisioning
# ==============================================================================
#
# Uncomment one block and replace the stub values with yours.


## Manual provisioning with connection string
#
# [provisioning]
# source = "manual"
# connection_string = "HostName=example.azure-devices.net;DeviceId=my-device;SharedAccessKey=YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGU="


## Manual provisioning with symmetric key
# [provisioning]
# source = "manual"
# iothub_hostname = "example.azure-devices.net"
# device_id = "my-device"
#
# [provisioning.authentication]
# method = "sas"
#
# device_id_pk = { value = "YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGU=" }     # inline key (base64), or...
# device_id_pk = { uri = "file:///var/secrets/device-id.key" }                  # file URI, or...
# device_id_pk = { uri = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" } # PKCS#11 URI


## Manual provisioning with X.509 certificate
# [provisioning]
# source = "manual"
# iothub_hostname = "example.azure-devices.net"
# device_id = "my-device"
#
# [provisioning.authentication]
# method = "x509"
#
## identity key
# identity_pk = "file:///var/secrets/device-id.key.pem"              # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" # PKCS#11 URI
#
## identity certificate
# identity_cert = "file:///var/secrets/device-id.pem"                # file URI, or...
# [provisioning.authentication.identity_cert]                        # dynamically issued via...
# method = "est"                                                     # - EST
# method = "local_ca"                                                # - a local CA
# common_name = "my-device"                                          # with the given common name, or...
# subject = { L = "AQ", ST = "Antarctica", CN = "my-device" }        # with the given DN fields


## DPS provisioning with symmetric key
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net/"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "symmetric_key"
# registration_id = "my-device"
#
# symmetric_key = { value = "YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGVudGl0eS1zZXJ2aWNlfGF6aW90LWlkZW50aXR5LXNlcg==" } # inline key (base64), or...
# symmetric_key = { uri = "file:///var/secrets/device-id.key" }                                                          # file URI, or...
# symmetric_key = { uri = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" }                                         # PKCS#11 URI


## DPS provisioning with X.509 certificate
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net/"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "x509"
# registration_id = "my-device"
#
## identity key
# identity_pk = "file:///var/secrets/device-id.key.pem"              # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" # PKCS#11 URI
#
## identity certificate
# identity_cert = "file:///var/secrets/device-id.pem"                # file URI, or...
# [provisioning.attestation.identity_cert]                           # dynamically issued via...
# method = "est"                                                     # - EST
# method = "local_ca"                                                # - a local CA
# common_name = "my-device"                                          # with the given common name, or...
# subject = { L = "AQ", ST = "Antarctica", CN = "my-device" }        # with the given DN fields
#
## Uncomment the section below to enable automatic renewal of the device ID certificate.
## Auto-renewal requires a known certificate issuance method. This generally means that
## 'method' is either 'est' or 'local_ca'.
##
## IMPORTANT:
## ONLY ENABLE AUTO-RENEWAL IF THIS DEVICE IS CONFIGURED FOR CA-BASED DPS ENROLLMENT.
## USING AUTO-RENEWAL FOR AN INDIVIDUAL ENROLLMENT WILL CAUSE THE DEVICE TO BE UNABLE
## TO REPROVISION.
# [provisioning.attestation.identity_cert.auto_renew]
# rotate_key = true
# threshold = "80%"
# retry = "4%"


## DPS provisioning with TPM
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net/"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "tpm"
# registration_id = "my-device"


# ==============================================================================
# Cert issuance
# ==============================================================================
#
# If you configured any dynamically issued certs above, uncomment the block
# corresponding to the issuance method and replace the stub values with yours.


# Cert issuance via EST
# ---------------------

# [cert_issuance.est]
# trusted_certs = [
#     "file:///var/secrets/est-id-ca.pem",
# ]
#
# [cert_issuance.est.auth]
# username = "estuser"
# password = "estpwd"
#
# # EST ID cert already on device, or...
# identity_cert = "file:///var/secrets/est-id.pem"
#
# identity_pk = "file:///var/secrets/est-id.key.pem"            # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=est-id?pin-value=1234" # PKCS#11 URI
#
# # EST ID cert requested via EST bootstrap ID cert
# bootstrap_identity_cert = "file:///var/secrets/est-bootstrap-id.pem"
#
# bootstrap_identity_pk = "file:///var/secrets/est-bootstrap-id.key.pem"            # file URI, or...
# bootstrap_identity_pk = "pkcs11:slot-id=0;object=est-bootstrap-id?pin-value=1234" # PKCS#11 URI
#
## Controls the renewal of EST identity certs. These certs are issued by the EST server after
## initial authentication with the bootstrap cert and managed by Certificates Service.
# [cert_issuance.est.identity_auto_renew]
# rotate_key = true
# threshold = "80%"
# retry = "4%"
#
# [cert_issuance.est.urls]
# default = "https://example.org/.well-known/est"


# Cert issuance via local CA
# --------------------------

# [cert_issuance.local_ca]
# cert = "file:///var/secrets/local-ca.pem"
#
# pk = "file:///var/secrets/local-ca.key.pem"            # file URI, or...
# pk = "pkcs11:slot-id=0;object=local-ca?pin-value=1234" # PKCS#11 URI


# ==============================================================================
# PKCS#11
# `==============================================================================`
#
# If you used any PKCS#11 URIs above, uncomment the next block and
# replace the stub values with your PKCS#11 configuration.

# [aziot_keys]
# pkcs11_lib_path = "/usr/lib/libmypkcs11.so"
# pkcs11_base_slot = "pkcs11:slot-id=0?pin-value=1234"
[provisioning]
 source = "manual"
 connection_string = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
Updated config.toml

```
# ==============================================================================
# Hostname
# ==============================================================================
#
# Uncomment the next line to override the default hostname of this device.
#
# hostname = "my-device"

# ==============================================================================
# Local Gateway Hostname
# ==============================================================================
#
# If this device is running in a nested deployment, uncomment the next line to
# set the local gateway hostname of this device.
#
# local_gateway_hostname = "my-parent-device"

# ==============================================================================
# Cloud Timeout and Retry Behavior
# ==============================================================================
#
# These settings control the timeout and retries for cloud operations, such as
# communication with DPS during provisioning or IoT Hub for module identity creation.
#
# cloud_timeout_sec is the deadline (in seconds) for a network request (such as
# an HTTP request) to the aforementioned cloud services. A response from the cloud
# must be received before this deadline, or the request will fail as timed out.
#
# cloud_retries controls how many times a request may be retried should it fail.
# The client will always send at least one attempt, so its value will be the number
# of retries after the first attempt should that fail (i.e. cloud_retries = 2
# means that the client will make a total of 3 attempts).
#
# cloud_timeout_sec = 10
# cloud_retries = 1

# ==============================================================================
# Provisioning
# ==============================================================================
#
# Uncomment one block and replace the stub values with yours.


## Manual provisioning with connection string
#
# [provisioning]
# source = "manual"
# connection_string = "HostName=example.azure-devices.net;DeviceId=my-device;SharedAccessKey=YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGU="


## Manual provisioning with symmetric key
# [provisioning]
# source = "manual"
# iothub_hostname = "example.azure-devices.net"
# device_id = "my-device"
#
# [provisioning.authentication]
# method = "sas"
#
# device_id_pk = { value = "YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGU=" }     # inline key (base64), or...
# device_id_pk = { uri = "file:///var/secrets/device-id.key" }                  # file URI, or...
# device_id_pk = { uri = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" } # PKCS#11 URI


## Manual provisioning with X.509 certificate
# [provisioning]
# source = "manual"
# iothub_hostname = "example.azure-devices.net"
# device_id = "my-device"
#
# [provisioning.authentication]
# method = "x509"
#
## identity key
# identity_pk = "file:///var/secrets/device-id.key.pem"              # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" # PKCS#11 URI
#
## identity certificate
# identity_cert = "file:///var/secrets/device-id.pem"                # file URI, or...
# [provisioning.authentication.identity_cert]                        # dynamically issued via...
# method = "est"                                                     # - EST
# method = "local_ca"                                                # - a local CA
# common_name = "my-device"                                          # with the given common name, or...
# subject = { L = "AQ", ST = "Antarctica", CN = "my-device" }        # with the given DN fields


## DPS provisioning with symmetric key
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net/"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "symmetric_key"
# registration_id = "my-device"
#
# symmetric_key = { value = "YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGVudGl0eS1zZXJ2aWNlfGF6aW90LWlkZW50aXR5LXNlcg==" } # inline key (base64), or...
# symmetric_key = { uri = "file:///var/secrets/device-id.key" }                                                          # file URI, or...
# symmetric_key = { uri = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" }                                         # PKCS#11 URI


## DPS provisioning with X.509 certificate
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net/"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "x509"
# registration_id = "my-device"
#
## identity key
# identity_pk = "file:///var/secrets/device-id.key.pem"              # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" # PKCS#11 URI
#
## identity certificate
# identity_cert = "file:///var/secrets/device-id.pem"                # file URI, or...
# [provisioning.attestation.identity_cert]                           # dynamically issued via...
# method = "est"                                                     # - EST
# method = "local_ca"                                                # - a local CA
# common_name = "my-device"                                          # with the given common name, or...
# subject = { L = "AQ", ST = "Antarctica", CN = "my-device" }        # with the given DN fields
#
## Uncomment the section below to enable automatic renewal of the device ID certificate.
## Auto-renewal requires a known certificate issuance method. This generally means that
## 'method' is either 'est' or 'local_ca'.
##
## IMPORTANT:
## ONLY ENABLE AUTO-RENEWAL IF THIS DEVICE IS CONFIGURED FOR CA-BASED DPS ENROLLMENT.
## USING AUTO-RENEWAL FOR AN INDIVIDUAL ENROLLMENT WILL CAUSE THE DEVICE TO BE UNABLE
## TO REPROVISION.
# [provisioning.attestation.identity_cert.auto_renew]
# rotate_key = true
# threshold = "80%"
# retry = "4%"


## DPS provisioning with TPM
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net/"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "tpm"
# registration_id = "my-device"


# ==============================================================================
# Cert issuance
# ==============================================================================
#
# If you configured any dynamically issued certs above, uncomment the block
# corresponding to the issuance method and replace the stub values with yours.


# Cert issuance via EST
# ---------------------

# [cert_issuance.est]
# trusted_certs = [
#     "file:///var/secrets/est-id-ca.pem",
# ]
#
# [cert_issuance.est.auth]
# username = "estuser"
# password = "estpwd"
#
# # EST ID cert already on device, or...
# identity_cert = "file:///var/secrets/est-id.pem"
#
# identity_pk = "file:///var/secrets/est-id.key.pem"            # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=est-id?pin-value=1234" # PKCS#11 URI
#
# # EST ID cert requested via EST bootstrap ID cert
# bootstrap_identity_cert = "file:///var/secrets/est-bootstrap-id.pem"
#
# bootstrap_identity_pk = "file:///var/secrets/est-bootstrap-id.key.pem"            # file URI, or...
# bootstrap_identity_pk = "pkcs11:slot-id=0;object=est-bootstrap-id?pin-value=1234" # PKCS#11 URI
#
## Controls the renewal of EST identity certs. These certs are issued by the EST server after
## initial authentication with the bootstrap cert and managed by Certificates Service.
# [cert_issuance.est.identity_auto_renew]
# rotate_key = true
# threshold = "80%"
# retry = "4%"
#
# [cert_issuance.est.urls]
# default = "https://example.org/.well-known/est"


# Cert issuance via local CA
# --------------------------

# [cert_issuance.local_ca]
# cert = "file:///var/secrets/local-ca.pem"
#
# pk = "file:///var/secrets/local-ca.key.pem"            # file URI, or...
# pk = "pkcs11:slot-id=0;object=local-ca?pin-value=1234" # PKCS#11 URI


# ==============================================================================
# PKCS#11
# ==============================================================================
#
# If you used any PKCS#11 URIs above, uncomment the next block and
# replace the stub values with your PKCS#11 configuration.

# [aziot_keys]
# pkcs11_lib_path = "/usr/lib/libmypkcs11.so"
# pkcs11_base_slot = "pkcs11:slot-id=0?pin-value=1234"
[provisioning]
 source = "manual"
 connection_string = "xxxxxxxxxxxxxx"

# ==============================================================================
# Default Edge Agent
# ==============================================================================
#
# If you need to override the parameters of the default Edge Agent module,
# uncomment this section and replace the values in this section with your own.
#
# Note that the agent.config.createOptions field is specified as
# a TOML inline table. This format looks similar to JSON but it is not JSON.
# See https://toml.io/en/v1.0.0#inline-table for documentation.

 [agent]
 name = "edgeAgent"
 type = "docker"
# imagePullPolicy = "..."   # "on-create" or "never". Defaults to "on-create"

 [agent.config]
 image = "mcr.microsoft.com/azureiotedge-agent:1.3"
 createOptions = { HostConfig = { Binds = ["/iotedge/storage:/iotedge/storage"] } }

# [agent.config.auth]
# serveraddress = "example.azurecr.io"
# username = "username"
# password = "password"

 [agent.env]
# "RuntimeLogLevel" = "debug"
 "UpstreamProtocol" = "AmqpWs"
 "https_proxy" = "xxxxxxx"
# "storageFolder" = "/iotedge/storage"

```

**Comment by fcabrera23** [comment] 2022-11-14 14:20
Hi,

Closing this issue - The root cause was related to Static IP being used. To avoid issues with IP ranges, use 172 prefixes instead of 169.

Thanks
Francisco

**Closed by fcabrera23** 2022-11-14 14:20 UTC
