### ISSUE TITLE
File Sharing seems not working on documentation specified build of Windows 10

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#217] opened 2023-01-05 22:05 UTC
Hi Team,

Documentation of eflow file share is telling , file sharing feature is available in build 19044 and above. (Windows 10)

But today prepared an azure virtual machine with build 19045 + all updates installed. Observing Filesharing is not working.

1 . Could you advise, on is this feature is backported to Windows 10 ? if so on which build.
2. What is the tentative time line for this feature for Windows Server 2019 or 2022 (as our customers on server os machines and looking for this feature).

Note: on windows 11 with required build it's working as expected.

![image](https://user-images.githubusercontent.com/50254283/210888717-5a2f3488-c500-4e0a-9cd3-467de40c49d2.png)

**Comment by fcabrera23** [comment] 2023-01-06 14:47
Hi @post2vishwa,

Thanks for reaching out. We are currently investigating an issue with the newer version caused by the needed backporting. Our goal is to make folder sharing available for Win10/11 and Win Server 2019/2022.  I'll keep you updated next week with our progress. 

Thanks,
Francisco

**Comment by post2vishwa** [comment] 2023-01-06 16:14
Hi @Francisco,

Thanks much for update.

Regards,
Vishwa

**Comment by maggiojoe2** [comment] 2023-02-13 16:00
Are there any updates on the backport for Windows 10? I've seen on other issues there seem to be mentions of bugs found early in December and then in January, but am not seeing any other updates.

**Comment by fcabrera23** [comment] 2023-02-13 20:55
HI @maggiojoe2,

We are finalizing the development and expect to have this release end of this month.  We are sorry that our target date was moved twice, but our sharing mechanism depends on work that is being done across multiple teams.

Thanks,
Francisco

**Comment by fcabrera23** [comment] 2023-03-06 23:45
Hi @maggiojoe2, @post2vishwa,

This was fixed with EFLOW [1.4.4.03033 LTS](https://github.com/Azure/iotedge-eflow/releases/tag/1.4.4.03033) release.

Thanks,
Francisco

**Closed by fcabrera23** 2023-03-06 23:45 UTC
Labels: bug

**Comment by post2vishwa** [comment] 2023-03-08 17:10
Hi @fcabrera23 ,

Verified this on Win 10 22 H2 Latest and File Sharing is working now.

Though official documentation is not mentioned as a trial and error verified on Win 2022 Server Latest build, but it didn't work as expected which fine.

Down the line backporting to one of Server Operating systems as well useful (Win 2019 or Win 2022). 

Thanks much for backporting this to Win10.

Regards,
Vishwa
