### ISSUE TITLE
E-Flow - disk sharing with modules

### ISSUE THREAD

**Issue by mjeannin2** [Azure/iotedge-eflow#3] opened 2021-02-11 09:06 UTC
Hello,

I'm testing the new Eflow version of IotEdge.
I'm facing a subject. I need to share hosts informations with module.
Does exist a powershell script or a documentation to share a disk with the VM then with the docker.
Is it plan ?

If it doesn't exist, I will follow the standard way to share host disk with Hyper-V VM.

Thanks for your feedback,
Regards,
Maxime.

**Comment by TerryWarwick** [comment] 2021-02-18 05:34
@mjeannin2 ,

I would not expect you to be asked for a password unless for some reason the SSH key is not getting passed in properly.  Can you tell us a little about this deployment?  What edition / version of Windows are you using on the host?  Is the host actually a VM rather than running directly on physical hardware?  Are you running SSH from the localhost or remotely from another system?  Please provide step by step details so that we can reproduce the behavior that you are experiencing.  It would also be valuable for us to understand exactly what you are trying to accomplish in case we have other thoughts on how to accomplish it or perhaps even determine that we need to build some sort of functionality in for the future to make this easier.

Terry

**Comment by mjeannin2** [comment] 2021-02-18 08:21
Hello

Yes, I'm copying some configuration files used by the module with a disk binding.
So I'm trying to copy files to the dedicated place into the VM 
I execute a schedule task to copy this files with a dedicated script :
scp.exe -i "C:\Program Files\Azure IoT Edge\id_rsa" "C:\Program Files (x86)\Sentinel\iotconfig.ini" iotedge-user@192.168.1.101:/home/iotedge-user 


About the host, it is a Windows workstation (not a VM neither an Azure compute) : 
Windows version is 10.0.17763.437

Not sure it can help you but when I try to execute the command 
 Ssh-EflowVm, I receive this message : 

[02/18/2021 09:04:38] Exception caught!!!

 - wssagent is unreachable, please retry... at line 1627

When I try to connect to the Eflow VM from the host using the address given by Hyper-V and using the key file, it asks me the password

So in order to recap, I see 2 problems : 
- one about the wssagent
- one about SSH connexion - An idea about this one is that I gave some extended rights to the iotedge-user folder in the VM (0777) in order to access from the module. Maybe, SSH do not like that the key files are accessible from everybody in the VM

Regards
Maxime

**Comment by ms-mahuber** [comment] 2021-02-22 18:12
- wssdagent: For some reason the wssdagent service is not running. This is hasn't been seen so far because the service should always start and restart automatically, i.e., it should always be reachable.
- SSH key file: You would get an SSH error that says the permissions on the key are not correct and it would refuse to connect at all.

Taking all the errors into account, it seems to me that there might have been some issues at deploy time?

Also, in the scp command above, are you sure this copies iotconfig.ini into the /home/iotedge-user folder? It looks to me like it would attempt to overwrite the 'iotedge-user' folder as a file (I may be wrong on this but have you tried /home/iotedge-user/iotconfig.ini?)

**Comment by TerryWarwick** [comment] 2021-02-23 03:15
@mjeannin2 ,

An easy way to check the status of WSSDAgent is to execute the following command at an elevated PowerShell command prompt.

Get-Service wssdagent

If it is not running then it appears that you may have a larger issue with your specific EFLOW deployment.  

Run the following command to check the status of the EFLOW virtual machine

Get-VM | Where-Object { $_.Name -like '*EFLOW'}

Terry

**Comment by TerryWarwick** [comment] 2021-03-15 23:40
@mjeannin2, 

Were you able to overcome the disk sharing issue?  If you are still experiencing an issue with this please help us understand exactly what you are experiencing.  If you are no longer having an issue with this, please Close the issue report.

Thank you

Terry Warwick

**Comment by ytzh101** [comment] 2021-06-03 14:06
> @mjeannin2 ,
> 
> An easy way to check the status of WSSDAgent is to execute the following command at an elevated PowerShell command prompt.
> 
> `Get-Service wssdagent`
> 
> If it is not running then it appears that you may have a larger issue with your specific EFLOW deployment.
> 
> Run the following command to check the status of the EFLOW virtual machine
> 
> `Get-VM | Where-Object { $_.Name -like '*EFLOW'}`
> 
> Terry

I am facing the same issue here. 
`PS C:\windows\system32> Ssh-EflowVm   
                                                                                                                                                                                                          [06/03/2021 09:57:31] Exception caught!!!
                                                                                                                                                                                                        - wssagent is unreachable, please retry... at line 1682`

Following your suggestions, 
`PS C:\windows\system32> Get-Service wssdagent  ` 
                                                                                                                                                                                                `Status   Name               DisplayName                                                                                 ------   ----               -----------                                                                                 Stopped  wssdagent          WSSD Agent Service             `                                                                                                                                                                                                                                                                                                             

`PS C:\windows\system32> Get-VM | Where-Object { $_.Name -like '*EFLOW'}                `     
                                                                                                                                                    `Name                 State   CPUUsage(%) MemoryAssigned(M) Uptime           Status             Version                  ----                 -----   ----------- ----------------- ------           ------             -------                  USWE-2LFRPV2-L-EFLOW Running 0           1024              00:06:06.5930000 Operating normally 9.0  `

I am having a larger issue here. How can I set the WSSDAgent to automatically restart? 
Thanks for your help.

**Comment by ytzh101** [comment] 2021-06-03 15:14
> > @mjeannin2 ,
> > An easy way to check the status of WSSDAgent is to execute the following command at an elevated PowerShell command prompt.
> > `Get-Service wssdagent`
> > If it is not running then it appears that you may have a larger issue with your specific EFLOW deployment.
> > Run the following command to check the status of the EFLOW virtual machine
> > `Get-VM | Where-Object { $_.Name -like '*EFLOW'}`
> > Terry
> 
> I am facing the same issue here.
> `PS C:\windows\system32> Ssh-EflowVm [06/03/2021 09:57:31] Exception caught!!! - wssagent is unreachable, please retry... at line 1682`
> 
> Following your suggestions,
> `PS C:\windows\system32> Get-Service wssdagent `
> `Status Name DisplayName ------ ---- ----------- Stopped wssdagent WSSD Agent Service `
> 
> `PS C:\windows\system32> Get-VM | Where-Object { $_.Name -like '*EFLOW'} `
> `Name State CPUUsage(%) MemoryAssigned(M) Uptime Status Version ---- ----- ----------- ----------------- ------ ------ ------- USWE-2LFRPV2-L-EFLOW Running 0 1024 00:06:06.5930000 Operating normally 9.0 `
> 
> I am having a larger issue here. How can I set the WSSDAgent to automatically restart?
> Thanks for your help.

Update:
I fixed the WSSDAgent problem on my machine. 
In Windows10, run Services.msc as admin, find the WSSD Agent Service, set the Startup Type to Automatic. On the left, start the service, no reboot is needed.

**Comment by fcabrera23** [comment] 2021-06-08 13:19
@ytzh101,

That's great news - the WSSD Agent service should be automatic by default when installing EFLOW, but if for some reason it's not, then that's a great workaround.

**Closed by fcabrera23** 2021-06-08 13:19 UTC
Labels: enhancement
